# Generated by Django 4.2.7 on 2023-11-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_room_students_online_room_teacher_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AnnouncementFilesCourse',
        ),
    ]
